wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717077084
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 77
      3:
      - 13
      - 23
      4: 3.10.6
      5: 0.17.0
      6: 4.40.2
      8:
      - 5
      13: linux-x86_64
