name: Lint

on:
    push:
        branches:
            - dev

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                python-version: "3.10"

            - name: "Install dependencies"
              run: pip install -r requirements.dev.txt

            - name: "Format code"
              run: |
                black .
                isort .
                docformatter --in-place -r .

            - name: "Check for changes"
              id: git-check
              run: |
                git diff --quiet || echo "::set-output name=changes::true"

            - name: "Push changes"
              if: steps.git-check.outputs.changes == 'true'
              run: |
                git config --global user.name "GitHub Actions"
                git config --global user.email "actions@github.com"
                git add .
                git commit -m "Auto-format code"
                git push